-- SQLite
CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR (100) NOT NULL,
    LASTNAME VARCHAR (150) NOT NULL,
    PHONE VARCHAR (25),
    EMAIL VARCHAR (100) NOT NULL,
    ADDRESS VARCHAR (200) NOT NULL,
    CITY VARCHAR (100) NOT NULL,
    STATE VARCHAR (2) NOT NULL,
    BIRTH_DATE DATE NOT NULL
);

SELECT * FROM CUSTOMERS;





