-- SQLite
SELECT L.ID,
CUSTOMERS.NAME AS 'CUSTOMER',
CARS.NAME      AS 'CAR',
EMPLOYEES.NAME AS 'EMPLOYEE'
FROM LOCATIONS AS L

JOIN
CUSTOMERS ON (L.CUSTOMER_ID = CUSTOMERS.ID),
CARS      ON (L.CAR_ID = CARS.ID),
EMPLOYEES ON (L.EMPLOYEE_ID = EMPLOYEES.ID);

SELECT * FROM LOCATIONS;
