-- SQLite
CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL,
    YEAR INTEGER NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    KM INTEGER NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    BRAND_ID INTEGER NOT NULL,
    MODEL_ID INTEGER NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRAND(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODEL(ID)
);